services:
  - type: web
    name: smartdepedforms
    env: python
    plan: free
    region: singapore
    branch: main

    rootDir: SmartForms

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn SmartForms.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SmartForms.settings

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true

      - key: ALLOWED_HOSTS
        value: .onrender.com
