services:
  - type: web
    name: smartdepedforms-web
    env: python
    branch: main
    rootDir: SmartForms
    region: singapore
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn SmartForms.SmartForms.wsgi:application

    postDeploy: >
      python manage.py migrate
      python manage.py create_default_school &&
      python manage.py init_roles

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SmartForms.SmartForms.settings

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true
