services:
  - type: web
    name: smartdepedforms-web
    env: python
    branch: main
    rootDir: SmartForms
    region: singapore
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn config.wsgi:application

    postDeploy: >
      python manage.py migrate

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

      - key: DEBUG
        value: "False"

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: smartdepedforms-db
          property: connectionString

databases:
  - name: smartdepedforms-db
    plan: free
